# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 584c07a2a3d4cd69b4e88434829ef43b556b7ccd125d5b759dfff22f7ad58f3c072548fd94f1ecd880b226d402808c4e6f4cefc81e5fb575c50720941afb5242

test:
  secret_key_base: 5fd021206d509ab99c9e32256f94e509b3d694d2826d7c944e4e3f7e97d7c4ae11ea16d42af43806247002c487bfa8501a599aa3b8308582cace2fa94d5ae1f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
